[package]
name = "libuv"
version = "0.1.1"
authors = ["Stefan O'Rear <stefanor@cox.net>"]
repository = "https://github.com/sorear/libuv-rs"
description = "Native bindings to the libuv library"
license = "MIT"
# todo: readme, documentation, homepage, keywords?

[dependencies]
libc = "0.2.26"
